export { ActivateCard } from './Page1'
export { Balance } from './Page2'
export { NotFound } from './NotFound'
export { Terms } from './Page4'
export { Success } from './Page3'
export { Landing } from './Landing'